### ISSUE TITLE
Array not overrided

### ISSUE THREAD

**Issue by davidino** [namshi/node-nmconfig#8]
give a `base.yml` like:

``` yml
name: 'base'
shop:
 - 'ae'
 - 'sa'
 - 'me'
```

and a `live.yml` like:

``` yml
name: 'test'
shop:
 - 'me'
```

the expected result was:

``` yml
name: 'test'
shop:
 - 'me'
```

instead of:

``` yml
name: 'test'
shop:
 - 'ae'
 - 'sa'
 - 'me'
```

the array is not overriden
